skeleton *sculpt_human()
  {
  polygon pelvis[1] = bone_inv_triangle(.125,.07)
  *center = (foo->root,NULL,NULL,(0,0,0),(0,-.125,.07),matgen_ident,matgen_ident,FALSE,*pelvis,1)
  //(*up,*prev,*next,(off.x,off.y,off.z),(len.x,len.y,len.z),base,curr,drawline,*faces,n_polys)
  skeleton foo = (),!!!!!COMEBACKHERE!!!!!,((1,1,1),(0,0)))
  polygon skull[8] = bone_octohedron(.1)
  bone *cervical = spine(*center,*center,.66,17)
  bone *neck = spine(*cervical,*cervical,.125,7)
  bone *head = (*neck,*neck,NULL,(0,.1,0),(0,0,0),(1,matgen_ident,matgen_ident,FALSE,*skull,8)
  doublelink(*head)
  bone *lshoulder = (*cervical,*head,NULL,(0,0,0),(.142,0,0),matgen_z_deg(-90),matgen_ident,TRUE,NULL,0)
  doublelink(*lshoulder)
  bone *lwrist = arm(*lshoulder,*lshoulder,.3,-1)
  bone *lthumb = thumbphalanges(*lwrist,*lwrist,3,(0,0,45))
  bone *lcarple3 = (*lwrist,*lthumb,NULL,(1,0,0),(lwrist->len.x / M_PI,0,0),matgen_ident,matgen_ident,TRUE,NULL,0)
  doublelink(*lcarple3)
  bone *lfinger3 = handphalanges(*lcarple3,*lcarple3,3,(0,0,0)))
  bone *lcarple2 = (*lwrist,*lfinger3,NULL,(1,0,0),((lwrist->len.x / M_PI) * COS_PI_32,0,0),matgen_z_deg(11.25),matgen_ident,TRUE,NULL,0)
  doublelink(*lcarple2)
  bone *lfinger2 = handphalanges(*lcarple2,*lcarple2,3,(0,0,-11.25))
  bone *lcarple4 = (*lwrist,*lfinger2,NULL,(1,0,0),(lwrist->len.x / M_PI * COS_PI_32,0,0),matgen_z_deg(-11.25),matgen_ident,TRUE,NULL,0)
  doublelink(*lcarple4)
  bone *lfinger4 = handphalanges(*lcarple4,*lcarple4,3,(0,0,11.25)))
  bone *lcarple5 = (*lwrist,*lfinger4,NULL,(1,0,0),((lwrist->len.x / M_PI) * COS_PI_16,0,0),matgen_z_deg(-22.5),matgen_ident,TRUE,NULL,0)
  doublelink(*lcarple5)
  bone *lfinger5 = handphalanges(*lcarple5,*lcarple5,3,(0,0,22.5))
  bone *rshoulder = (*cervical,*lcarple5,NULL,(0,0,0),(.142,0,0),matgen_z_deg(90),matgen_ident,TRUE,NULL,0)
  doublelink(*rshoulder)
  bone *rwrist = arm(*rshoulder,*rshoulder,.3,1)
  bone *rthumb = thumbphalanges(*rwrist,*rwrist,3,(0,0,-45))
  bone *rcarple3 = (*rwrist,*rthumb,NULL,(1,0,0),(rwrist->len.x / M_PI,0,0),matgen_ident,matgen_ident,TRUE,NULL,0)
  doublelink(*rcarple3)
  bone *rfinger3 = handphalanges(*rcarple3,*rcarple3,3,(0,0,0)))
  bone *rcarple2 = (*rwrist,*rfinger3,NULL,(1,0,0),((rwrist->len.x / M_PI) * COS_PI_32,0,0),matgen_z_deg(-11.25),matgen_ident,TRUE,NULL,0)
  doublelink(*rcarple2)
  bone *rfinger2 = handphalanges(*rcarple2,*rcarple2,3,(0,0,11.25))
  bone *rcarple4 = (*rwrist,*rfinger2,NULL,(1,0,0),(rwrist->len.x / M_PI * COS_PI_32,0,0),matgen_z_deg(11.25),matgen_ident,TRUE,NULL,0)
  doublelink(*rcarple4)
  bone *rfinger4 = handphalanges(*rcarple4,*rcarple4,3,(0,0,-11.25)))
  bone *rcarple5 = (*rwrist,*rfinger4,NULL,(1,0,0),((rwrist->len.x / M_PI) * COS_PI_16,0,0),matgen_z_deg(22.5),matgen_ident,TRUE,NULL,0)
  doublelink(*rcarple5)
  bone *rfinger5 = handphalanges(*rcarple5,*rcarple5,3,(0,0,-22.5))
  
